name: Terraform Deploy GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy Infraestructura GCP
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GOOGLE_PROJECT: "proyectopruebasvale"
      GOOGLE_REGION: "us-central1"
      GOOGLE_ZONE: "us-central1-a"
      TF_WORKING_DIR: "."

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name:  Inicializar Terraform
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Plan de ejecución
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

      - name: Aplicar cambios
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan